export { default as ChangePassword } from "./ChangePassword";
export { default as ForgotPassword } from "./ForgotPassword";
export { default as FriendsClasses } from "./FriendsClasses";
export { default as Grades } from "./Grades";
export { default as Home } from "./Home";
export { default as LinkGoogleAccount } from "./LinkGoogleAccount";
export { default as Preferences } from "./Preferences";
export { default as SignIn } from "./SignIn";
export { default as SignUp } from "./SignUp";
