version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  cypress: cypress-io/cypress@1.23.0

jobs:
  install_and_test:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - codecov/upload:
          file: 'web/coverage/*.json'

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_and_test
      - cypress/install:
          executor: cypress/base-12-6-0
          yarn: true
          requires:
            - install_and_test
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          browser: chrome
          executor: cypress/browsers-chrome78-ff70
          post-install:
            - run: |
                set -x
                curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
            - setup_remote_docker
            - run: npm run setup
          build: 'npm run build'
          start: 'npm run start'
          wait-on: 'http://localhost:3000'
