version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  cypress: cypress-io/cypress@1.23.0

executors:
  node-mongo-redis:
    docker:
      - image: cypress/base:12.6.0
      - image: circleci/mongo:latest
      - image: circleci/redis:latest

jobs:
  install_and_test:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - codecov/upload:
          file: 'web/coverage/*.json'

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_and_test
      - cypress/install:
          executor: cypress/base-12-6-0
          yarn: true
          requires:
            - install_and_test
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          executor: node-mongo-redis
          build: 'npm run build'
          start: 'npm run start'
          wait-on: 'http://localhost:3000'
