version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  cypress: cypress-io/cypress@1.23.0

jobs:
  build:
    docker:
      - image: circleci/node:10.18.1
    working_directory: ~/mern
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - codecov/upload:
          file: 'web/coverage/*.json'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - cypress/install:
          name: 'Linux install'
          build: npm run build
          working_directory: ~/mern
          yarn: true
          requires:
            - build
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info
      - cypress/run:
          # name this job because we are running "cypress/run" several times
          # with different parameters
          name: '1 machine'
          # job will use workspace with code and dependencies
          # installed by the "install" job
          requires:
            - 'Linux install'
          browser: chrome
          executor: cypress/browsers-chrome78-ff70
          record: true # record results on Cypress dashboard
          start: 'npm run test:e2e' # start server before running tests
