version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  cypress: cypress-io/cypress@1.23.0

jobs:
  install_and_test:
    docker:
      - image: circleci/node:10.18.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - codecov/upload:
          file: 'web/coverage/*.json'

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_and_test
      - cypress/install:
          executor: cypress/base-12-6-0
          name: 'Linux install'
          build: cross-env CI=false npm run build
          yarn: true
          requires:
            - install_and_test
          post-steps:
            - run: npx cypress cache path
            - run: npx cypress cache list
            - run: npx cypress info
      - cypress/run:
          requires:
            - 'Linux install'
          browser: chrome
          executor: cypress/browsers-chrome78-ff70
          record: true # record results on Cypress dashboard
          start: 'npm run test:e2e' # start server before running tests
