export * from "./IAxiosErrorResponse";
export * from "./IEvaluation";
export * from "./IHomework";
export * from "./IRequestError";
export * from "./IScheduleEvent";
export * from "./ISignInCredentials";
export * from "./ISignUpCredentials";
export * from "./IToDo";
export * from "./IUser";
